### ISSUE TITLE
Some problems of SCOTII input files

### ISSUE THREAD

**Issue by Boston1212** [Taming-the-BEAST/SCOTTI-Tutorial#2]
Hi,
   Sorry to bother you,I want to know how to caculate the date in SCOTII's date_file.csv.Any advice would be helpful to me!Thanks!!!

**Comment by laduplessis** [comment]
Apologies for the slow reply. 

If you're using the Python script `SCOTTI_generate_xml.py` to create your XML file then you need to specify the dates as the time measured from some day 0 to the sampling time of each sequence. These times should be in the same time units you want to use for your clock rate (i.e. days for subs/site/day or years for subs/site/year etc.). 

In the tutorial we used dates specified in numbers of days from some arbitrary day 0 of the outbreak. You may find it easier to specify your dates in terms of years (where day 0 is the year 0 CE). To convert from a calendar date to a decimal you can use the R-package lubridate, e.g. `lubridate::decimal_date(lubridate::ymd("2020-03-02"))` should give you `2020.167` (alternatively you can just enter the sequences and their dates in BEAUti and copy down the decimal dates). 

The dates for the hostTimes file are similar. 

For any further questions I suggest you contact Nicola de Maio, the developer of SCOTTI.
